// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpAPicmmAUjkteumrySZ7B8Dq-yzO7sIA',
    appId: '1:93188565590:web:2ecb3ffe106c1ff56369f7',
    messagingSenderId: '93188565590',
    projectId: 'pampers-3rd-app-tfh-2025',
    authDomain: 'pampers-3rd-app-tfh-2025.firebaseapp.com',
    storageBucket: 'pampers-3rd-app-tfh-2025.firebasestorage.app',
    measurementId: 'G-4QD9D7LRSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuCssa-R2Qe1gsZBVXpMLB9rr-cXCxF0g',
    appId: '1:93188565590:android:5e4666f07fc1ee3f6369f7',
    messagingSenderId: '93188565590',
    projectId: 'pampers-3rd-app-tfh-2025',
    storageBucket: 'pampers-3rd-app-tfh-2025.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl-YoUxMwITswbWSjiCH0QrQNkx7DHcys',
    appId: '1:93188565590:ios:e0e1dc5cbaf9215e6369f7',
    messagingSenderId: '93188565590',
    projectId: 'pampers-3rd-app-tfh-2025',
    storageBucket: 'pampers-3rd-app-tfh-2025.firebasestorage.app',
    iosBundleId: 'com.example.fffApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl-YoUxMwITswbWSjiCH0QrQNkx7DHcys',
    appId: '1:93188565590:ios:e0e1dc5cbaf9215e6369f7',
    messagingSenderId: '93188565590',
    projectId: 'pampers-3rd-app-tfh-2025',
    storageBucket: 'pampers-3rd-app-tfh-2025.firebasestorage.app',
    iosBundleId: 'com.example.fffApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpAPicmmAUjkteumrySZ7B8Dq-yzO7sIA',
    appId: '1:93188565590:web:3035c5717b9854786369f7',
    messagingSenderId: '93188565590',
    projectId: 'pampers-3rd-app-tfh-2025',
    authDomain: 'pampers-3rd-app-tfh-2025.firebaseapp.com',
    storageBucket: 'pampers-3rd-app-tfh-2025.firebasestorage.app',
    measurementId: 'G-V3RBBHKZJY',
  );
}
