include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    avoid_catches_without_on_clauses: ignore
    avoid_futureor_void: ignore
    avoid_positional_boolean_parameters: ignore
    implementation_imports: ignore
    invalid_annotation_target: ignore
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
formatter:
  trailing_commas: preserve